#!/usr/bin/env bash

Black='\e[1;30m'       # Black
Red='\e[1;31m'         # Red
Green='\e[1;32m'       # Green
Yellow='\e[1;33m'      # Yellow
Blue='\e[1;34m'        # Blue
Purple='\e[1;35m'      # Purple
Cyan='\e[1;36m'        # Cyan
White='\e[1;37m'       # White
echo
sleep 1
echo -e " ${Red}Pleace wait...."
sleep 2
echo -e " ${Red}Running setup stylish..."
sleep 2
mkdir $HOME/.termux
mv $HOME/Stylish $PREFIX/share
chmod +x $PREFIX/share/Stylish/.stylish
ln -sf $PREFIX/share/Stylish/.stylish $PREFIX/bin/stylish

echo -e "${Purple} Done..
ketik stylish untuk run ${White}"
stylish
